using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using Zombera.Systems;
#if UNITY_EDITOR
using UnityEditor;
#endif

namespace Zombera.BuildingSystem
{
    [DisallowMultipleComponent]
    public sealed partial class EasyBuildRadialMenuInputBridge : MonoBehaviour
    {
        private const string BuildingControllerTypeName =
            "MindCodeInteractive.EasyBuildSystem.Framework.Code.Runtime.Systems.Controllers.BuildingController";
        private const string BuildingManagerTypeName =
            "MindCodeInteractive.EasyBuildSystem.Framework.Code.Runtime.Systems.Managers.BuildingManager";
        private const string BuildingModeEnumTypeName =
            "MindCodeInteractive.EasyBuildSystem.Framework.Code.Runtime.Systems.Controllers.States.BuildingMode";
        private const string BuildingInputTypeName =
            "MindCodeInteractive.EasyBuildSystem.Framework.Code.Runtime.Systems.Controllers.Inputs.BuildingInput";
        private const string BuildingSelectionActionTypeName =
            "MindCodeInteractive.EasyBuildSystem.Framework.Code.Runtime.UI.BuildingMenus.Implementations.Actions.BuildingSelectionAction";
        private const string BuildingRadialMenuUiTypeName =
            "MindCodeInteractive.EasyBuildSystem.Framework.Code.Runtime.UI.BuildingMenus.Implementations.BuildingRadialMenuUI";
        private const string PrefabModularCatalogFolder = "Assets/02_Shared/Prefabs/Building/Building Parts Modular";
        private const string GeneratedSpriteLibraryAssetPath = "Assets/Data/Building/BuildPrefabSpriteLibrary.asset";

        [Header("Input")]
        [SerializeField] private bool rightClickTogglesRadialMenu;
        [SerializeField] private bool ignoreRightClickWhenPointerOverUi;
        [SerializeField]
        private Key toggleRadialMenuKey = Key.B;
        [SerializeField]
        [Tooltip("When enabled, pressing the toggle key (default B) opens/closes the EasyBuild radial menu.")]
        private bool toggleRadialMenuWithKeyboard = true;
        [SerializeField]
        [Tooltip("Optional local builder mode source used to gate radial-menu right-click toggles.")]
        private BuildPlacementController buildPlacementController;
        [SerializeField]
        [Tooltip("When enabled, right-click only toggles the EasyBuild radial menu while local builder mode is active.")]
        private bool requireLocalBuilderModeForRadialToggle;
        [SerializeField]
        [Tooltip("When enabled, runtime forces B-key-only menu access and disables right-click toggles even if old serialized values differ.")]
        private bool enforceBKeyOnlyMenuAccess = true;

        [Header("Live Build Shortcuts")]
        [SerializeField]
        [Tooltip("While held in build mode, rotates the active preview clockwise at a fixed repeat rate.")]
        private bool enableHoldRotatePreview = true;
        [SerializeField] private Key holdRotatePreviewKey = Key.V;
        [SerializeField] [Min(0.02f)] private float holdRotateRepeatSeconds = 0.08f;

        [SerializeField]
        [Tooltip("Allows live height offset changes during build mode using keyboard keys.")]
        private bool enableRealtimeHeightHotkeys = true;
        [SerializeField] private Key heightUpPrimaryKey = Key.UpArrow;
        [SerializeField] private Key heightDownPrimaryKey = Key.DownArrow;
        [SerializeField] private Key heightUpAlternateKey = Key.Equals;
        [SerializeField] private Key heightDownAlternateKey = Key.Minus;
        [SerializeField] private Key heightUpNumpadKey = Key.NumpadPlus;
        [SerializeField] private Key heightDownNumpadKey = Key.NumpadMinus;
        [SerializeField] [Min(0.01f)] private float realtimeHeightStep = 0.25f;
        [SerializeField] [Min(0.02f)] private float realtimeHeightRepeatSeconds = 0.08f;

        [Header("Placement Height")]
        [SerializeField] [Min(0.01f)] private float placementHeightStep = 0.25f;
        [SerializeField] private Vector2 placementHeightRange = new(-6f, 6f);

        [Header("Startup Cleanup")]
        [SerializeField] private bool removeSampleBuildingGroupCubeOnPlay;
        [SerializeField] [Min(0f)] private float sampleArtifactCleanupDelaySeconds = 6f;
        [SerializeField] [Range(32, 2048)] private int sampleArtifactCleanupScanBatchSize = 256;

        [Header("Catalog Source")]
        [SerializeField] private bool restrictCatalogToExtensionFolders = true;
        [SerializeField]
        [Tooltip("Optional sprite library generated by the Building Icons tool. When a part reference is found here, HUD uses that sprite icon.")]
        private BuildPrefabSpriteLibrary buildPrefabSpriteLibrary;
        [SerializeField]
        [Tooltip("Defers extension catalog scanning until build UI is first opened to reduce startup hitching.")]
        private bool deferExtensionCatalogBuildUntilBuildUiActive = true;
        [SerializeField] private string[] extensionCatalogFolders =
        {
            PrefabModularCatalogFolder,
            "Assets/03_ThirdParty/Mind Code Interactive/Easy Build System/Packages/Extensions/Survival Blueprint",
            "Assets/03_ThirdParty/Mind Code Interactive/Easy Build System/Packages/Extensions/Survival Upgradable"
        };

        [Header("Radial Menu Presentation")]
        [SerializeField] [Range(0f, 0.5f)]
        private float radialMenuVerticalScreenOffsetPercent = 0.1f;

        [SerializeField] private bool radialMenuUsesUnscaledTime = true;

        [Header("Debug")]
        [SerializeField] private bool enableBridgeDebugLogs;
        [SerializeField] private bool verboseBridgeDebugLogs;
        [SerializeField]
        [Tooltip("Disable bridge diagnostics automatically in play mode to avoid startup hitching.")]
        private bool disableBridgeDiagnosticsInPlayMode = true;
        [SerializeField]
        [Tooltip("Emit focused placement diagnostics for part references matching the filter text.")]
        private bool enableFilteredPlacementDiagnostics;
        [SerializeField] private string placementDiagnosticsPartFilter = "barrel";
        [SerializeField] [Min(0.1f)]
        private float placementDiagnosticsRepeatIntervalSeconds = 0.4f;
        [SerializeField] [Min(0.1f)]
        private float ensureSelectedPartDiagnosticsIntervalSeconds = 2f;

        private object _cachedRadialMenu;
        private Type _cachedRadialMenuType;
        private RectTransform _cachedRadialMenuRect;
        private Vector2 _cachedRadialMenuBaseAnchoredPosition;
        private int _cachedRadialMenuScreenHeight = -1;
        private bool _cachedRadialMenuUnscaledConfigured;
        private EasyBuildCursorPlacementBinder _cachedCursorPlacementBinder;
        private bool _manualBuildModeActive;
        private Type _cachedBuildingControllerType;
        private Type _cachedBuildingManagerType;
        private Type _cachedBuildingModeType;
        private Type _cachedBuildingInputType;
        private Type _cachedSelectionActionType;
        private object _cachedBuildingController;
        private object _cachedBuildingInput;
        private PlayerInputController _cachedOwnerInputController;
        private bool _wasBuildUiActive;
        private bool _blockBuildToggleThisFrame;
        private int _currentHudSelectionIndex = -1;
        private float _nextControlsHelpRefreshAt;
        private string _cachedControlsHelpText;
        private float _nextRotateKeyRepeatAt;
        private float _nextHeightKeyRepeatAt;
        private float _nextRotateShortcutLogAt;
        private float _nextPlacementHeightLogAt;
        private readonly List<string> _filteredCatalogPartReferences = new(256);
        private readonly HashSet<string> _filteredCatalogPartReferenceSet = new(StringComparer.OrdinalIgnoreCase);
        private readonly Dictionary<string, float> _nextPlacementDiagnosticAtByKey =
            new(StringComparer.OrdinalIgnoreCase);
        private string _lastEnsureSelectedPartReference;
        private int _lastEnsureSelectedHudIndex = int.MinValue;
        private float _nextEnsureSelectedPartDiagnosticAt;
    #if UNITY_EDITOR
        private readonly Dictionary<string, string> _catalogPrefabNameByPartReference =
            new(StringComparer.OrdinalIgnoreCase);
        private bool _hasFilteredCatalogSnapshot;
        private int _lastFilteredCatalogManagerPartCount = -1;
        private int _lastExtensionCatalogSignature = int.MinValue;
        private float _nextFilteredCatalogRefreshAt;
    #endif

        public bool IsRadialMenuOpen
        {
            get
            {
                if (!TryResolveRadialMenu(out var radialMenu)) return false;

                return EasyBuildBridgeRadialMenuStateHelper.IsRadialMenuOpen(radialMenu);
            }
        }

        public bool IsBuildUiActive => _manualBuildModeActive || IsRadialMenuOpen;
        public int CurrentHudSelectionIndex => _currentHudSelectionIndex;

        /// <summary>
        ///     Legacy HUD reserved index 9 for "cancel" only when the active category had ≤9 part slots
        ///     (indices 0..8). Larger catalogs use index 9 as a real part — use <see cref="TryCancelBuildUi" /> for cancel.
        /// </summary>
        public const int LegacyHudCancelSlotIndex = 9;

        public int GetBuildCategoryCount()
        {
            if (IsUsingExtensionFolderFilter())
                return GetFilteredCatalogPartCount() > 0 ? 1 : 0;

            if (!TryResolveRadialMenu(out var radialMenu) || radialMenu == null)
            {
                return GetBuildItemCountFromManager() > 0 ? 1 : 0;
            }

            return EasyBuildBridgeRadialMenuStateHelper.GetBuildCategoryCount(radialMenu);
        }

        public int GetActiveBuildCategoryIndex()
        {
            if (IsUsingExtensionFolderFilter())
                return GetFilteredCatalogPartCount() > 0 ? 0 : -1;

            if (!TryResolveRadialMenu(out var radialMenu) || radialMenu == null) return -1;

            return EasyBuildBridgeRadialMenuStateHelper.GetActiveBuildCategoryIndex(
                radialMenu,
                ResolveActiveOrFirstCategory);
        }

        public bool TrySetActiveBuildCategory(int categoryIndex)
        {
            if (IsUsingExtensionFolderFilter())
                return categoryIndex == 0 && GetFilteredCatalogPartCount() > 0;

            if (categoryIndex < 0) return false;
            if (!TryResolveRadialMenu(out var radialMenu) || radialMenu == null)
            {
                BridgeLog($"Set category failed: radial menu unavailable (requested={categoryIndex})");
                return false;
            }

            if (!EasyBuildBridgeRadialMenuStateHelper.TrySetActiveBuildCategory(
                    radialMenu,
                    categoryIndex,
                    ResolveRadialCategoryByIndex))
            {
                BridgeLog($"Set category failed: category index not found ({categoryIndex})");
                return false;
            }

            BridgeLog($"Active category set to {categoryIndex}");
            return true;
        }

        public int GetBuildItemCount()
        {
            if (IsUsingExtensionFolderFilter())
                return GetFilteredCatalogPartCount();

            if (!TryResolveRadialMenu(out var radialMenu) || radialMenu == null)
            {
                BridgeLog("GetBuildItemCount using manager fallback: radial menu unavailable", true);
                return GetBuildItemCountFromManager();
            }

            if (!EasyBuildBridgeRadialMenuStateHelper.TryGetBuildItemCountFromActiveCategory(
                    radialMenu,
                    ResolveActiveOrFirstCategory,
                    out var count))
                return 0;

            if (count > 0) return count;

            BridgeLog("GetBuildItemCount using manager fallback: active category has zero slots", true);
            return GetBuildItemCountFromManager();
        }


        public string GetBuildControlsHelpText()
        {
            if (Time.unscaledTime < _nextControlsHelpRefreshAt && !string.IsNullOrWhiteSpace(_cachedControlsHelpText))
                return _cachedControlsHelpText;

            _cachedControlsHelpText = ComposeBuildControlsHelpText();
            _nextControlsHelpRefreshAt = Time.unscaledTime + 1f;
            return _cachedControlsHelpText;
        }

        public bool TryAdjustPlacementHeight(int direction)
        {
            if (direction == 0) return false;

            return TryAdjustPlacementHeight(direction * placementHeightStep);
        }

        public bool TryAdjustPlacementHeight(float delta)
        {
            var settings = ResolveSelectedPartPlacementSettings();
            return EasyBuildBridgePlacementHeightHelper.TryAdjustPlacementHeight(
                settings,
                delta,
                placementHeightRange,
                message => BridgeLog(message),
                ref _nextControlsHelpRefreshAt,
                ref _nextPlacementHeightLogAt);
        }

        public float GetPlacementHeightOffset()
        {
            var settings = ResolveSelectedPartPlacementSettings();
            return EasyBuildBridgePlacementHeightHelper.GetPlacementHeightOffset(settings);
        }

        public bool TrySetPlacementMode()
        {
            return TrySetControllerModeCandidates("Placement");
        }

        public bool TrySetDestructionMode()
        {
            return TrySetControllerModeCandidates("Destruction", "Destroy", "Demolition", "Removal");
        }

        public bool TrySetEditionMode()
        {
            return TrySetControllerModeCandidates("Edition", "Edit", "Adjustment", "Selection");
        }

        public bool TrySetReplacementMode()
        {
            return TrySetControllerModeCandidates("Replacement", "Replace", "Replacer");
        }

        public string GetCurrentControllerModeName()
        {
            var controller = ResolveBuildingControllerInstance();
            return EasyBuildBridgeRuntimeResolverHelper.ResolveCurrentControllerModeName(controller);
        }


        public string GetHudItemLabel(int hudItemIndex)
        {
            if (hudItemIndex < 0) return null;

            if (TryResolveFilteredHudPart(hudItemIndex, out var filteredPart))
            {
                var filteredDisplayName = ResolvePartDisplayName(filteredPart);
                return string.IsNullOrWhiteSpace(filteredDisplayName)
                    ? $"Item {hudItemIndex + 1}"
                    : filteredDisplayName;
            }

            var slotCount = GetBuildItemCount();
            if (hudItemIndex == LegacyHudCancelSlotIndex && slotCount <= LegacyHudCancelSlotIndex)
                return "Cancel [Esc]";

            var part = ResolveHudPart(hudItemIndex);
            var partDisplayName = ResolvePartDisplayName(part);
            if (!string.IsNullOrWhiteSpace(partDisplayName))
                return partDisplayName;

            if (TryResolveRadialSlotVisualData(hudItemIndex, out var slotLabel, out _)
                && !string.IsNullOrWhiteSpace(slotLabel))
            {
                return slotLabel.Trim();
            }

            return $"Item {hudItemIndex + 1}";
        }

        public Texture2D GetHudItemTexture(int hudItemIndex)
        {
            if (hudItemIndex < 0) return null;

            if (TryResolveFilteredHudPart(hudItemIndex, out var filteredPart))
            {
                if (TryResolveSpriteFromLibrary(filteredPart, out _))
                    return null;

                return EasyBuildBridgePartDataHelper.ResolveMainTextureFromPart(filteredPart);
            }

            var slotCount = GetBuildItemCount();
            if (hudItemIndex == LegacyHudCancelSlotIndex && slotCount <= LegacyHudCancelSlotIndex) return null;

            if (TryResolveRadialSlotVisualData(hudItemIndex, out _, out var slotTexture) && slotTexture != null)
                return slotTexture;

            var part = ResolveHudPart(hudItemIndex);
            if (part == null) return null;

            if (TryResolveSpriteFromLibrary(part, out _))
                return null;

            return EasyBuildBridgePartDataHelper.ResolveMainTextureFromPart(part);
        }

        /// <summary>
        ///     Some Easy Build catalog rows store a <see cref="Sprite" /> on the slot/action instead of a standalone <see cref="Texture2D" />.
        ///     Use for Unity UI <see cref="UnityEngine.UI.Image" /> when <see cref="GetHudItemTexture" /> returns null.
        /// </summary>
        public Sprite GetHudItemSprite(int hudItemIndex)
        {
            if (hudItemIndex < 0) return null;

            var slotCount = GetBuildItemCount();
            if (hudItemIndex == LegacyHudCancelSlotIndex && slotCount <= LegacyHudCancelSlotIndex) return null;
            if (hudItemIndex >= slotCount) return null;

            if (TryResolveHudSpriteFromLibrary(hudItemIndex, out var librarySprite))
                return librarySprite;

            if (!TryResolveRadialMenu(out var radialMenu) || radialMenu == null) return null;

            return EasyBuildBridgeHudVisualHelper.ResolveSpriteFromRadialMenu(radialMenu, hudItemIndex);
        }


        public bool TryCancelBuildUi()
        {
            ForceCloseBuildUi();
            BridgeLog("Build UI cancel requested");
            return true;
        }

        public bool TryActivateHudItem(int hudItemIndex)
        {
            if (hudItemIndex < 0) return false;

            if (TrySelectFilteredPartByHudIndex(hudItemIndex))
            {
                _currentHudSelectionIndex = hudItemIndex;
                SetPlacementMode();
                _manualBuildModeActive = true;
                BridgeLog($"HUD item activated (filtered): index={hudItemIndex}");
                return true;
            }

            var slotCount = GetBuildItemCount();

            // Legacy: index 9 meant "cancel" only when the category had at most 9 slot indices (0..8).
            if (hudItemIndex == LegacyHudCancelSlotIndex && slotCount <= LegacyHudCancelSlotIndex)
                return TryCancelBuildUi();

            if (slotCount <= 0 || hudItemIndex >= slotCount)
            {
                BridgeLog($"Activate HUD item failed: index={hudItemIndex}, slotCount={slotCount}");
                return false;
            }

            if (!TrySelectPartByHudIndex(hudItemIndex))
            {
                BridgeLog($"Activate HUD item failed selecting part: index={hudItemIndex}");
                return false;
            }

            _currentHudSelectionIndex = hudItemIndex;
            SetPlacementMode();
            _manualBuildModeActive = true;
            BridgeLog($"HUD item activated: index={hudItemIndex}");
            return true;
        }


    }
}
