sonar.projectKey=Pancakeshake_Zombera
sonar.organization=pancakeshake

sonar.sources=Assets
sonar.exclusions=\
  Assets/ThirdParty/**,\
  Assets/UMA/**,\
  Assets/Universal Sound FX/**,\
  Assets/Animations/**,\
  Assets/StreamingAssets/**

sonar.cs.file.suffixes=.cs
