namespace Zombera.World.CityPipeline.WorldBuilder
{
    /// <summary>Ordered world-build pipeline stage identifiers (1–41).</summary>
    public enum WorldBuildStageId : byte
    {
        ResetGeneratedWorld = 1,
        EnsureWorldBuilderStack = 44,
        ValidateWorldProfile = 2,
        CreateGlobalWorldPlan = 3,
        AllocateTerrainGrid = 4,
        GenerateBaseLandforms = 5,
        ReserveCityPads = 47,
        ErodeLandforms = 6,
        SolveHydrology = 7,
        CarveWaterFeatures = 8,
        BuildOceanSurfaces = 43,
        ClassifyBiomesAndBuildability = 9,
        SelectCitySitesAndLandmarks = 10,
        ApplyCityPads = 11,
        PaintNaturalSurfaces = 12,
        PlanRoadsAndHighways = 13,
        RefineRoadsAgainstTerrain = 14,
        ResolveWaterCrossings = 15,
        ResolveMountainTunnels = 46,
        StampInfrastructureTerrain = 16,
        BuildEasyRoadsMeshes = 17,
        SyncInfrastructureSurfaces = 18,
        GenerateNamedAreas = 19,
        GenerateDistrictLots = 20,
        PlaceBuildings = 21,
        GenerateLotTerrain = 22,
        GenerateFences = 23,
        GenerateRoadMarkings = 24,
        GenerateTrafficLights = 25,
        GenerateStreetSigns = 26,
        BuildParks = 27,
        GenerateStreetLamps = 28,
        GeneratePowerLines = 29,
        BuildWaterSurfaces = 30,
        PlaceWildernessPois = 31,
        PlaceWildernessNature = 32,
        PlaceCityTrees = 33,
        GenerateStreetFurniture = 34,
        GenerateParkedCars = 35,
        ConfigureSkyAndWeather = 36,
        InitializeEnvironmentState = 37,
        BindWeatherConsumers = 38,
        FinalizeTerrainTiles = 39,
        QueueNavMesh = 40,
        GenerateCityFootpaths = 42,
        PlanInterCityHighways = 45,
        ValidateAndPublish = 41
    }
}
